export const SOCIAL_CONFIG = {
  linkedin: 'dhiraj-gede',
  researchGate: '',
  facebook: '',
  instagram: '',
  reddit: '',
  threads: '',
  youtube: '',
  udemy: '',
  dribbble: '',
  behance: '',
  stackoverflow: '',
  skype: '',
  telegram: '',
  phone: '',
};
