export const THEME_CONFIG = {
  defaultTheme: 'lofi',
  disableSwitch: false,
  respectPrefersColorScheme: false,
  displayAvatarRing: true,
  themes: [
    'light',
    'dark',
    'cupcake',
    'bumblebee',
    'emerald',
    'corporate',
    'synthwave',
    'retro',
    'cyberpunk',
    'valentine',
    'halloween',
    'garden',
    'forest',
    'aqua',
    'lofi',
    'pastel',
    'fantasy',
    'wireframe',
    'black',
    'luxury',
    'dracula',
    'cmyk',
    'autumn',
    'business',
    'acid',
    'lemonade',
    'night',
    'coffee',
    'winter',
    'dim',
    'nord',
    'sunset',
    'procyon',
  ],
  customTheme: {
    primary: '#fc055b',
    secondary: '#219aaf',
    accent: '#e8d03a',
    neutral: '#2A2730',
    'base-100': '#E3E3ED',
    '--rounded-box': '3rem',
    '--rounded-btn': '3rem',
  },
};
